name: Test

on:
  pull_request:
  push:
    branches:
      - main
    tags: ['*']

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          skip-unshallow: "true"
      - name: Check gofmt
        run: |
          set -x

          if [ ! -z $(gofmt -l .) ]
          then
            echo 'Make sure to run "gofmt -s -w ." before commit!' && exit 1
          fi
      - name: Check go vet
        run: |
          set -x
          make vet
      - name: Run static check
        run: |
          set -x
          go install honnef.co/go/tools/cmd/staticcheck@latest
          make static
      - name: Check gosec
        run: |
          set -x
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          make sec
      - name: Lint and test
        run: make test
